import { Box, Flex, Heading, Image, Input, InputGroup, InputLeftElement, InputRightAddon, Text } from '@chakra-ui/react'
import axios from 'axios';
import React, { useState } from 'react'
import { VscSend } from "react-icons/vsc";
import { CircularProgress, CircularProgressLabel } from '@chakra-ui/react'
import logo from "../assets/logo.png"
const Answers = () => {
    const [keyword, setKeyword] = useState("")
    const [answer, setanswer] = useState("")
    const [loading, setLoading] = useState(false)
    const [error, setError] = useState(false)
    const handleClick = () => {
        const data = {
            keyword
        }
        setLoading(true)
        axios.post(`https://shaikhgpt.onrender.com/ask`, data).then((res) => {
            setanswer(res.data.ans)
            setLoading(false)
            setError(false)
        }).catch((err) => {
            setLoading(false)
            setError(true)
            console.log(err)
        })

    }
    return (
        <Box bgColor={"#312949"}>
            <br />
            <Heading w={"95%"} m={"auto"} fontFamily={"cursive"} textAlign={"center"}>بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ</Heading>
            <Box w={"95%"} m={"auto"} mt={"8px"} mb={"8px"}>
                <hr />
            </Box>
            <Heading w={"95%"} m={"auto"} fontFamily={"cursive"} textAlign={"center"} fontSize={{ xl: "25px", lg: "25px", md: "20px", sm: "20px", base: "20px" }}>In the name of Allah, the Most Gracious, the Most Merciful</Heading>
            <Flex justifyContent={"center"} m={"20px"}>
                <Image src={logo} w={{ xl: "300px", lg: "300px", md: "300px", sm: "200px", base: "200px" }} />
            </Flex>

            <Box pb={"10px"} w={{ xl: "60%", lg: "60%", md: "80%", sm: "90%", base: "90%" }} m={"auto"}>
                <Heading fontFamily={"cursive"} fontSize={"18px"} textAlign={"center"} as={"h4"}>Ask your question here...</Heading>
            </Box>

            <Box w={{ xl: "60%", lg: "60%", md: "80%", sm: "90%", base: "90%" }} m={"auto"}>
                <InputGroup>
                    <Input value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="Try typing... 5 pillars of islam?..etc." />
                    <InputRightAddon bgColor="#0400ff36" _hover={{ cursor: "pointer" }} onClick={handleClick} color={"#f6ff00"} children={<VscSend size={"25px"} />} as={"b"} />
                </InputGroup>
            </Box>
            <br />
            {
                loading
                    ?
                    <Flex justifyContent={"center"}>
                        <CircularProgress isIndeterminate color='green.300' />
                    </Flex>
                    :
                    <Box display={answer ? "block" : "none"} w={{ xl: "60%", lg: "60%", md: "80%", sm: "90%", base: "90%" }} m={"auto"}>
                        <Heading textAlign={"center"} fontFamily={"cursive"} fontSize={"24px"} color={"#ffdd00"}>Shaikh GPT Answer</Heading>
                        <br />
                        <Box border={"1px solid white"} bgColor={"#00000054"} p={"10px"} borderRadius={"10px"}>
                            <Text>{answer}</Text>
                        </Box>
                    </Box>
            }
            <br />
            <Box fontSize={"18px"} w={{ xl: "60%", lg: "60%", md: "80%", sm: "90%", base: "90%" }} m={"auto"}>
                <Text><b style={{ color: "#ffdd00" }}>Warning:</b> Don't relay only on this or any AI generated answers, always cross check the answer with authentic books or ask with Islamic scholars.</Text>
                <br />
                <br />
                <Text><b style={{ color: "#ffdd00" }}>Disclaimer:</b> ShaikhGPT is an AI(Artificial Intelligence) tool powered by GPT-3.5, a large language model, hence any answer generated by ShaikhGPT is not guaranteed to be true factually and the answer can be incomplete also,Matters pertaining to Islam are to be consulted by real Islamic scholars.</Text>
                <br />
                <Text><b style={{ color: "#ffdd00" }}>Note:</b> The Developers of this website are in no way resposible for the responses being generated by this ShaikhGPT AI.</Text>
            </Box>
            <br />
        </Box>
    )
}

export default Answers
